config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :ingredients
    resources :recipe_methods
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :measurement, inclusion: { in: ['grams', 'ml', 'item/s', 'tbsp', 'cup/s', 'pinch/s']}

  MEASUREMENT_OPTIONS = ['grams', 'ml', 'item/s', 'tbsp', 'cup/s', 'pinch/s']

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_methods
  has_many :ingredients, dependent: :delete_all
  has_many :recipe_methods, dependent: :delete_all
  belongs_to :user

  scope :filter_by_name, -> (name) { where name: name}
  scope :filter_by_cuisine, -> (cuisine) { where cuisine: cuisine}

  scope :filter_by_query, ->(query) {
    return nil  if query.blank?

    terms = query.downcase.split('+')


    terms = terms.map { |e|
    (e.tr("*", "%") + "%").gsub(/%+/, "%")
    }

    num_or_conds = 2
    where(
      terms.map { |_term|
        "(LOWER(recipes.name) LIKE ? OR LOWER(recipes.cuisine) LIKE ?)"
      }.join(" AND "),
      *terms.map { |e| [e] * num_or_conds }.flatten,
    )
  }
  
  scope :filter_by_ingred, ->(ingred) {
    ingred = ingred.downcase.split(',')
    request = "((\"" + ingred[0] + "\" IN (SELECT LOWER(ingredient) FROM ingredients WHERE recipes.id = ingredients.recipe_id))"
    for i in 1..ingred.length()-1
      request << " AND (\"" + ingred[i]  + "\" IN (SELECT LOWER(ingredient) FROM ingredients WHERE recipes.id = ingredients.recipe_id))"
    end
    request << ")"
    puts request
    where(request)
  }
end

app/models/recipe_method.rb
class RecipeMethod < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many  :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_recipe
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET recipes/1/ingredients
  def index
    @ingredients = @recipe.ingredients
  end

  # GET recipes/1/ingredients/1
  def show
  end

  # GET recipes/1/ingredients/new
  def new
    @ingredient = @recipe.ingredients.build
  end

  # GET recipes/1/ingredients/1/edit
  def edit
  end

  # POST recipes/1/ingredients
  def create
    @ingredient = @recipe.ingredients.build(ingredient_params)

    if @ingredient.save
      redirect_to(@ingredient.recipe)
    else
      render action: 'new'
    end
  end

  # PUT recipes/1/ingredients/1
  def update
    if @ingredient.update(ingredient_params)
      redirect_to(@ingredient.recipe)
    else
      render action: 'edit'
    end
  end

  # DELETE recipes/1/ingredients/1
  def destroy
    @ingredient.destroy

    redirect_to(@ingredient.recipe)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find(params[:recipe_id])
    end

    def set_ingredient
      @ingredient = @recipe.ingredients.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ingredient_params
      params.require(:ingredient).permit(:ingredient, :measurement, :quantity, :recipe_id)
    end
end

app/controllers/recipe_methods_controller.rb
class RecipeMethodsController < ApplicationController
  before_action :set_recipe
  before_action :set_recipe_method, only: [:show, :edit, :update, :destroy]

  # GET recipes/1/recipe_methods
  def index
    @recipe_methods = @recipe.recipe_methods
  end

  # GET recipes/1/recipe_methods/1
  def show
  end

  # GET recipes/1/recipe_methods/new
  def new
    @recipe_method = @recipe.recipe_methods.build
  end

  # GET recipes/1/recipe_methods/1/edit
  def edit
  end

  # POST recipes/1/recipe_methods
  def create
    @recipe_method = @recipe.recipe_methods.build(recipe_method_params)

    if @recipe_method.save
      redirect_to(@recipe_method.recipe)
    else
      render action: 'new'
    end
  end

  # PUT recipes/1/recipe_methods/1
  def update
    if @recipe_method.update(recipe_method_params)
      redirect_to(@recipe_method.recipe)
    else
      render action: 'edit'
    end
  end

  # DELETE recipes/1/recipe_methods/1
  def destroy
    @recipe_method.destroy

    redirect_to(@recipe_method.recipe)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find(params[:recipe_id])
    end

    def set_recipe_method
      @recipe_method = @recipe.recipe_methods.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recipe_method_params
      params.require(:recipe_method).permit(:step, :details, :recipe_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(nil)
    filtering_params(params).each do |key, value|
      @recipes = @recipes.public_send("filter_by_#{key}", value) if value.present?
    end
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @ingredient = @recipe.ingredients.build
    @recipe_method = @recipe.recipe_methods.build
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
    @ingredient = @recipe.ingredients.build
    @recipe_method = @recipe.recipe_methods.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :cuisine, :method)
    end

      # A list of the param names that can be used for filtering the Product list
    def filtering_params(params)
      params.slice(:query, :ingred)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for([@ingredient.recipe, @ingredient]) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ingredient %><br />
    <%= f.text_field :ingredient, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :measurement %><br />
    <%= f.select :measurement, Ingredient::MEASUREMENT_OPTIONS, {}, {:class => 'form-select' } %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Add Ingredient", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', @recipe %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Ingredient</th>
    <th>Measurement</th>
    <th>Quantity</th>
    <th>Recipe</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.ingredient %></td>
    <td><%= ingredient.measurement %></td>
    <td><%= ingredient.quantity %></td>
    <td><%= ingredient.recipe %></td>
    <td><%= link_to 'Show', [ingredient.recipe, ingredient] %></td>
    <td><%= link_to 'Edit', edit_recipe_ingredient_path(ingredient.recipe, ingredient) %></td>
    <td><%= link_to 'Destroy', [ingredient.recipe, ingredient], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_recipe_ingredient_path(params[:recipe_id]) %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_ingredients_path(@ingredient.recipe) %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ingredient:</b>
  <%= @ingredient.ingredient %>
</p>

<p>
  <b>Measurement:</b>
  <%= @ingredient.measurement %>
</p>

<p>
  <b>Quantity:</b>
  <%= @ingredient.quantity %>
</p>

<p>
  <b>Recipe:</b>
  <%= @ingredient.recipe %>
</p>


<%= link_to 'Edit', edit_recipe_ingredient_path(@ingredient.recipe, @ingredient) %> |
<%= link_to 'Back', recipe_ingredients_path(@ingredient.recipe) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet", href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "rails-ujs" %>
    <%= csrf_meta_tag %>
  </head>

  <body>
    <div class="container pt-5">
      <p class="alert"><%= alert %></p>
      <div class="card">
        <div class="card-body">
          <%= yield %>
        </div>  
      </div>
    </div>
  </body>
</html>

app/views/recipe_methods/_form.html.erb
<%= form_for([@recipe_method.recipe, @recipe_method]) do |f| %>
  <% if @recipe_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_method.errors.count, "error") %> prohibited this recipe_method from being saved:</h2>

      <ul>
      <% @recipe_method.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :step, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_field :details, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Add Step", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipe_methods/edit.html.erb
<h1>Editing Method</h1>

<%= render 'form' %>


<%= link_to 'Back', @recipe %>

app/views/recipe_methods/index.html.erb
<h1>Listing recipe_methods</h1>

<table>
  <tr>
    <th>Step</th>
    <th>Details</th>
    <th>Recipe</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipe_methods.each do |recipe_method| %>
  <tr>
    <td><%= recipe_method.step %></td>
    <td><%= recipe_method.details %></td>
    <td><%= recipe_method.recipe %></td>
    <td><%= link_to 'Show', [recipe_method.recipe, recipe_method] %></td>
    <td><%= link_to 'Edit', edit_recipe_recipe_method_path(recipe_method.recipe, recipe_method) %></td>
    <td><%= link_to 'Destroy', [recipe_method.recipe, recipe_method], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe method', new_recipe_recipe_method_path(params[:recipe_id]) %>

app/views/recipe_methods/new.html.erb
<h1>New recipe_method</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_recipe_methods_path(@recipe_method.recipe) %>

app/views/recipe_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Step:</b>
  <%= @recipe_method.step %>
</p>

<p>
  <b>Details:</b>
  <%= @recipe_method.details %>
</p>

<p>
  <b>Recipe:</b>
  <%= @recipe_method.recipe %>
</p>


<%= link_to 'Edit', edit_recipe_recipe_method_path(@recipe_method.recipe, @recipe_method) %> |
<%= link_to 'Back', recipe_recipe_methods_path(@recipe_method.recipe) %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div>
    <%= form.label :cuisine, style: "display: block" %>
    <%= form.text_field :cuisine,  class: "form-control" %>
  </div>
  <div>
    <%= form.submit "Create Recipe", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="card">
    <div class"card-body">
      <h5 class="card-title">
        <p><%= recipe.name %></p>
      </h5>
      <p>
        Cuisine:
        <%= recipe.cuisine %>
      </p>
      <p>
        <%= link_to "See more", recipe %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipe", @recipe %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<%= button_to "logout", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>

<form action="/recipes"> 
  <div class="input-group">
    <input class="form-control" type="text" placeholder="Search.." name="query">
    <input class="form-control" type="text" placeholder="Ingredients.." name="ingred">
    <button class="btn btn-primary" type="submit">Search</button>
  </div>
</form>
<br>
  

<h2 class="card-title d-flex justify-content-between">
  <span>Recipes</span>
  <%= link_to "New recipe", new_recipe_path, class: "btn btn-primary" %>
</h2>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>


    

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card-title d-flex justify-content-between"><h1>
<span><%= @recipe.name %></span>
<%= link_to "Edit", edit_recipe_path(@recipe), class: 'btn btn-warning' %>
<%= link_to "Delete", @recipe, method: :delete, class: 'btn btn-danger' , data: { confirm: 'Are you sure?' } %>
<%= link_to "Back", recipes_path(@recipe) , class: 'btn btn-primary' %>
</h1></div>

<hr>

<h2>Ingredients</h2>

<table>
  <tr>
    <th>Ingredient</th>
    <th>Quantity</th>
    <th>Measurement</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipe.ingredients.each do |ingredient| %>
  <% if ingredient.persisted? %>
    <tr>
      <td><%= ingredient.ingredient %></td>
      <td><%= ingredient.quantity %></td>
      <td><%= ingredient.measurement %></td>
      <td><%= link_to 'Edit', edit_recipe_ingredient_path(ingredient.recipe, ingredient) %></td>
      <td><%= link_to 'Remove', [ingredient.recipe, ingredient], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %> 
<% end %>
</table>

<br />

<h6>New ingredient</h6>

<%= form_for([@ingredient.recipe, @ingredient]) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-group">
    <div class="field">
      <%= f.text_field :ingredient,  placeholder: "Ingredient..", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.text_field :quantity,  placeholder: "Quantity..", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.select :measurement, Ingredient::MEASUREMENT_OPTIONS, {}, {:class => 'form-select' } %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Add Ingredient", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>


<br>

<hr>

<h2>Method</h2>

<table>
  <tr>
    <th>Step</th>
    <th>Details</th>
    <th></th>
    <th></th>
  </tr>

<% @recipe.recipe_methods.each do |recipe_method| %>
  <% if recipe_method.persisted? %>
    <tr>
      <td><%= recipe_method.step %></td>
      <td><%= recipe_method.details %></td>
      <td><%= link_to 'Edit', edit_recipe_recipe_method_path(recipe_method.recipe, recipe_method) %></td>
      <td><%= link_to 'Remove', [recipe_method.recipe, recipe_method], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %> 
<% end %>
</table>

<br />
<hr>

<h6>Add Step</h6>

<%= form_for([@recipe_method.recipe, @recipe_method]) do |f| %>
  <% if @recipe_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_method.errors.count, "error") %> prohibited this recipe_method from being saved:</h2>

      <ul>
      <% @recipe_method.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-group">
    <div class="field">
      <%= f.number_field :step, placeholder: "Step..", class: "form-control" %>
    </div>
    <div class="field">
      <%= f.text_field :details,  placeholder: "Details..", class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "Add Step", class: "btn btn-primary"%>
    </div>
  </div>
<% end %>